name: Install Packages
on:
  workflow_dispatch:

jobs:
  install-required-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Inputs validation check
        run: |
          npm install -g pnpm